# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            David Hadley
tagline:          ''
description:      'Physicist.'
url:              http://davehadley.co.uk

baseurl:          /

author:
  name:           'David Hadley'
  url:            http://davehadley.co.uk

# Custom vars
version:          2.2.0

github:
  repo:           https://github.com/davehadley/davehadley.github.io

gems: [jekyll-gist]
